export const COMMENT_EMOTION_GROUPS = [
  {
    key: "kaomoji",
    label: "颜文字",
    items: [
      "|´・ω・)ノ",
      "ヾ(≧∇≦*)ゝ",
      "(☆ω☆)",
      "（╯‵□′）╯︵┴─┴",
      "￣﹃￣",
      "(/ω＼)",
      "∠( ᐛ 」∠)＿",
      "(๑•̀ㅁ•́ฅ)",
      "→_→",
      "୧(๑•̀⌄•́๑)૭",
      "٩(ˊᗜˋ*)و",
      "(ノ°ο°)ノ",
      "(´இ皿இ｀)",
      "⌇●﹏●⌇",
      "(ฅ´ω`ฅ)",
      "(╯°A°)╯︵○○○",
      "φ(￣∇￣o)",
      "ヾ(´･ ･｀｡)ノ\"",
      "( ง ᵒ̌皿ᵒ̌)ง⁼³₌₃",
      "(ó﹏ò｡)",
      "Σ(っ °Д °;)っ",
      "( ,,´･ω･)ﾉ\"(´っω･｀｡)",
      "╮(╯▽╰)╭",
      "o(*////▽////*)q",
      "＞﹏＜",
      "( ๑´•ω•) \"(ㆆᴗㆆ)",
    ],
  },
  {
    key: "emoji",
    label: "Emoji",
    items: [
      "😂",
      "😀",
      "😅",
      "😊",
      "🙂",
      "🙃",
      "😌",
      "😍",
      "😘",
      "😜",
      "😝",
      "😏",
      "😒",
      "🙄",
      "😳",
      "😡",
      "😔",
      "😫",
      "😱",
      "😭",
      "💩",
      "👻",
      "🙌",
      "🖕",
      "👍",
      "😶",
      "🙏",
      "🍦",
      "🍉",
      "😣",
    ],
  },
  {
    key: "dinosaur",
    label: "小恐龙",
    items: [
      ":dinosaur-shy:",
      ":dinosaur-daze:",
      ":dinosaur-sweat:",
      ":dinosaur-proud:",
      ":dinosaur-powerless:",
      ":dinosaur-pouting:",
      ":dinosaur-eating:",
      ":dinosaur-ok:",
      ":dinosaur-doubt:",
      ":dinosaur-depressed:",
      ":dinosaur-close-eyes:",
      ":dinosaur-sleeping:",
      ":dinosaur-puzzled:",
      ":dinosaur-agree:",
      ":dinosaur-crazy:",
      ":dinosaur-angry:",
    ],
  },
  {
    key: "flower",
    label: "花!",
    description: "Source: github.com/k4yt3x/flowerhd",
    items: [
      ":flower-flower:",
      ":flower-grass:",
      ":flower-leaf:",
      ":flower-star:",
      ":flower-sun:",
      ":flower-moon:",
      ":flower-water:",
      ":flower-heihei:",
      ":flower-lemon:",
      ":flower-birthday:",
      ":flower-sea:",
      ":flower-vegetable:",
      ":flower-tile:",
      ":flower-utf:",
    ],
  },
];
